### ISSUE TITLE
Unit of electron beam dose / Algorithm

### ISSUE THREAD

**Issue by uvwatshu** [sdickreuter/EvoDose#4]
Hi!
I am very interested in the program for implementing the correction of the proximity effect of electron beams! In your algorithm, the calculation of the exposure dose is also obtained through discrete convolution of the initial dose at the exposure point and the Point Spread Function (PSF). In many papers, it is referred to as energy deposition density with the unit of eV/nm^2, whereas the dose obtained after convolution in our algorithm is in uC/nm^2. Is there any unit conversion between these two? Because in the subsequent steps, such as lithography, some lithography models will be used, and their unit is mJ/nm^2, which can be converted from eV/nm^2.
Thanks for publishing your code!!!
Huang

**Comment by sdickreuter** [comment]
Hi Huang,

You're welcome, I'm always happy when others find my stuff useful!

Its been a while  (6 years) since I worked on that stuff though, so take this with a grain of salt:
I guess you could just multiply the total charge with the accelerating voltage of your EBL system to get the total energy that was directed at the target. Which you can than convert to eV.
But I'm not sure if this is really the "energy deposition density" as that sounds like the actual energy that was deposited in the target, which will be different than the total energy directed at the target.

Also a hint for you (which you probably already know):
It is important to measure the PSF of your EBL system and use these values for the algorithm. The PSF will be different depending on the accelerating voltage, thickness and type of your resist, substrate and probably other settings of your EBL system.

**Comment by uvwatshu** [comment]
Thanks! I have solved this problem now！Your suggestions are very helpful for me!!! And I am working for combined deep learning with traditional dose correction algorithm right now!

**Comment by sdickreuter** [comment]
You are welcome!
That is an interesting project, conventional proximity correction is very time consuming, so an neuronal net could be much faster.
